export enum GuildFeature {
    InviteSplash = "INVITE_SPLASH",
    VIPRegions = "VIP_REGIONS",
    VanityURL = "VANITY_URL",
    Verified = "VERIFIED",
    Partnered = "PARTNERED",
    Community = "COMMUNITY",
    Commerce = "COMMERCE",
    Newws = "NEWS",
    Discoverable = "DISCOVERABLE",
    Featurable = "FEATURABLE",
    AnimatedIcon = "ANIMATED_ICON",
    Banner = "BANNER",
    WelcomeScreenEnabled = "WELCOME_SCREEN_ENABLED",
    MemberVerificationGateEnabled = "MEMBER_VERIFICATION_GATE_ENABLED",
    PreviewEnabled = "PREVIEW_ENABLED",
}
